<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="/proj/en/gdp/tests/testdate.xsl" type="text/xsl"?>
<?xml-stylesheet href="/xsl/guide.xsl" type="text/xsl"?>

<!DOCTYPE doc [
  <!ELEMENT doc (date+, lang)>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT lang (code+)>
      <!ELEMENT code (#PCDATA)>
]>

<doc>
<date>2004-12-31</date>
<date>2004-11-01</date>
<date>2004-10-02</date>
<date>2004-09-03</date>

<lang>
  <code>en</code>
  <code>fr</code>
  <code>cs</code>
  <code>ro</code>
  <code>ru</code>
  <code>sv</code>
  <code>tr</code>
  <code>nl</code>
  <code>da</code>
  <code>de</code>
  <code>fi</code>
  <code>es</code>
  <code>pt_br</code>
  <code>hu</code>
  <code>ja</code>
  <code>ko</code>
  <code>zh_cn</code>
  <code>zh_tw</code>
  <code>el</code>
  <code>id</code>
  <code>it</code>
  <code>pl</code>
  <code>vi</code>
  <code>lt</code>
  <code>sr</code>
  <code>he</code>
  <code>bg</code>
</lang>
</doc>
