<?xml version='1.0' encoding='UTF-8' standalone='yes'?> 
<?xml-stylesheet href="/xsl/useflags.xsl" type='text/xsl'?>
<?xml-stylesheet href="/xsl/guide.xsl" type='text/xsl'?>
<!DOCTYPE useflags [
<!ELEMENT useflags (date, global, local)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT global (flag+)>
<!ELEMENT local (category+)>
<!ELEMENT category (package+)>
<!ELEMENT package (flag+)>
<!ELEMENT flag (#PCDATA)>
<!ATTLIST flag name CDATA #REQUIRED>
<!ATTLIST package name CDATA #REQUIRED>
<!ATTLIST category name CDATA #REQUIRED>
]>
<useflags>
<date>2005-11-16</date>
<global>
<flag name="3dfx"><![CDATA[Adds support for 3dfx video cards to XFree86. See: voodoo3]]></flag>
<flag name="3dnow"><![CDATA[Adds support for 3dnow multimedia processor instructions]]></flag>
<flag name="X"><![CDATA[Adds support for X11]]></flag>
<flag name="Xaw3d"><![CDATA[Adds support of the 3d athena widget set]]></flag>
<flag name="a52"><![CDATA[Enables support for decoding ATSC A/52 streams used in DVD]]></flag>
<flag name="aac"><![CDATA[Enables support for MPEG-4 AAC Audio]]></flag>
<flag name="aalib"><![CDATA[Adds support for media-libs/aalib (ASCII-Graphics Library)]]></flag>
<flag name="accessibility"><![CDATA[Adds support for accessibility (eg 'at-spi' library)]]></flag>
<flag name="acl"><![CDATA[Adds support for Access Control Lists]]></flag>
<flag name="acpi"><![CDATA[Adds support for Advanced Configuration and Power Interface]]></flag>
<flag name="adabas"><![CDATA[Adds support for the Adabas database engine]]></flag>
<flag name="adns"><![CDATA[Adds support for the adns DNS client library]]></flag>
<flag name="afs"><![CDATA[Adds OpenAFS support (distributed file system)]]></flag>
<flag name="aim"><![CDATA[Enable AIM IM protocol support]]></flag>
<flag name="alsa"><![CDATA[Adds support for media-libs/alsa-lib (Advanced Linux Sound Architecture)]]></flag>
<flag name="altivec"><![CDATA[Adds support for optimizations for G4 and G5/ppc970 processors]]></flag>
<flag name="apache"><![CDATA[Chooses Apache1 support when a package optionally supports Apache1]]></flag>
<flag name="apache2"><![CDATA[Chooses Apache2 support when a package supports both Apache1 and Apache2]]></flag>
<flag name="apm"><![CDATA[Adds APM (Advanced Power Management) support]]></flag>
<flag name="arts"><![CDATA[Adds support for aRts: the KDE sound daemon]]></flag>
<flag name="audiofile"><![CDATA[Adds support for libaudiofile where applicable]]></flag>
<flag name="avi"><![CDATA[Adds avifile (Library for avi) support]]></flag>
<flag name="bash-completion"><![CDATA[Enable bash-completion support]]></flag>
<flag name="bcmath"><![CDATA[Adds support for libbcmath]]></flag>
<flag name="berkdb"><![CDATA[Adds support for sys-libs/db (Berkeley DB for MySQL)]]></flag>
<flag name="bidi"><![CDATA[Enables bidirectional language support]]></flag>
<flag name="bindist"><![CDATA[Flag to enable or disable options for prebuilt (GRP)  packages (eg. due to licensing issues)]]></flag>
<flag name="birdstep"><![CDATA[Adds support for the Birdstep Database Server]]></flag>
<flag name="blas"><![CDATA[adds support for the virtual/blas numerical library]]></flag>
<flag name="bluetooth"><![CDATA[Enable Bluetooth Support]]></flag>
<flag name="bmp"><![CDATA[Adds beep media player support. Mainly used to support bmp plugins in xmms, though also used for generic BMP support.]]></flag>
<flag name="bonobo"><![CDATA[Adds support for gnome-base/bonobo (Gnome CORBA interfaces)]]></flag>
<flag name="bootstrap"><![CDATA[!!internal use only!! DO NOT SET THIS FLAG YOURSELF!, used during original system bootstrapping]]></flag>
<flag name="boundschecking"><![CDATA[add bounds checking patch by Haj Ten Brugge, this will DISABLE the hardened PIE+SSP patches]]></flag>
<flag name="build"><![CDATA[!!internal use only!! DO NOT SET THIS FLAG YOURSELF!, used for creating build images and the first half of bootstrapping.]]></flag>
<flag name="bzip2"><![CDATA[Use the bzlib compression library]]></flag>
<flag name="calendar"><![CDATA[Adds support for calendars (not using mcal!)]]></flag>
<flag name="canna"><![CDATA[Adds support for the Canna kana to kanji conversion engine]]></flag>
<flag name="caps"><![CDATA[Use Linux capabilities library to control privileges.]]></flag>
<flag name="cdb"><![CDATA[Adds support for the CDB database engine from the author of qmail]]></flag>
<flag name="cdinstall"><![CDATA[Copies files from the CD rather than asking the user to copy them, mostly used with games]]></flag>
<flag name="cdparanoia"><![CDATA[Enables cdparanoia support]]></flag>
<flag name="cdr"><![CDATA[Adds support for CD writer hardware]]></flag>
<flag name="chasen"><![CDATA[Enable chasen support]]></flag>
<flag name="cjk"><![CDATA[Adds support for Multi-byte character languages (Chinese, Japanese, Korean)]]></flag>
<flag name="clamav"><![CDATA[Adds support for Clam AntiVirus software (usually with a plugin)]]></flag>
<flag name="cpdflib"><![CDATA[Adds support for clibpdf]]></flag>
<flag name="crypt"><![CDATA[Add support for encryption -- using mcrypt or gpg where applicable]]></flag>
<flag name="cscope"><![CDATA[Enables cscope interface -- in vim for example]]></flag>
<flag name="ctype"><![CDATA[Enables ctype functions ]]></flag>
<flag name="cups"><![CDATA[Add support for CUPS (Common Unix Printing System)]]></flag>
<flag name="curl"><![CDATA[Adds support for client-side URL transfer library]]></flag>
<flag name="curlwrappers"><![CDATA[Adds support for using curl in streams]]></flag>
<flag name="db2"><![CDATA[Enables support for IBM DB2 database server]]></flag>
<flag name="dba"><![CDATA[Enables dbm-compatible layers]]></flag>
<flag name="dbase"><![CDATA[Adds support for dbase file format]]></flag>
<flag name="dbm"><![CDATA[Adds support for generic DBM databases.]]></flag>
<flag name="dbmaker"><![CDATA[Adds support for dbmaker database server]]></flag>
<flag name="dbus"><![CDATA[Enable dbus support for anything that needs it (gpsd, gnomemeeting, etc)]]></flag>
<flag name="dbx"><![CDATA[Adds database abstraction layer]]></flag>
<flag name="debug"><![CDATA[Tells configure and the makefiles to build for debugging. Effects vary across packages, but generally it will at least add -g to CFLAGS. Remember to set FEATURES=nostrip too]]></flag>
<flag name="dedicated"><![CDATA[Adds support for dedicated game servers (some packages do not provide clients and servers at the same time)]]></flag>
<flag name="dga"><![CDATA[Adds DGA Support (Xfree86) (DGA=Direct Graphic Access)]]></flag>
<flag name="dio"><![CDATA[Adds direct i/o support]]></flag>
<flag name="directfb"><![CDATA[Adds support for DirectFB layer (library for FB devices)]]></flag>
<flag name="doc"><![CDATA[Adds extra documentation (API, Javadoc, etc)]]></flag>
<flag name="dri"><![CDATA[Enable direct rendering: used for accelerated 3D and some 2D, like DMA]]></flag>
<flag name="dts"><![CDATA[Enables libdts (DTS Coherent Acoustics decoder) support]]></flag>
<flag name="dv"><![CDATA[Enables support for a codec used by many camcorders]]></flag>
<flag name="dvb"><![CDATA[Adds support for DVB (Digital Video Broadcasting)]]></flag>
<flag name="dvd"><![CDATA[Adds support for DVDs]]></flag>
<flag name="dvdr"><![CDATA[Adds support for DVD writer hardware (e.g. in xcdroast)]]></flag>
<flag name="dvdread"><![CDATA[Enables usage of Ogle's libdvdread for DVD playback]]></flag>
<flag name="eds"><![CDATA[Enables support for Evolution-Data-Server(eds)]]></flag>
<flag name="emacs"><![CDATA[Adds support for GNU Emacs]]></flag>
<flag name="emacs-w3"><![CDATA[Add support for Emacs/W3 where applicable]]></flag>
<flag name="emboss"><![CDATA[Adds support for the European Molecular Biology Open Software Suite]]></flag>
<flag name="empress"><![CDATA[Adds support for the Empress database server]]></flag>
<flag name="empress-bcs"><![CDATA[Adds local access support for the Empress database server]]></flag>
<flag name="emul-linux-x86"><![CDATA[Pull in binary support libraries for x86 applications]]></flag>
<flag name="encode"><![CDATA[Adds support for encoding of audio or video files]]></flag>
<flag name="esd"><![CDATA[Adds support for media-sound/esound (Enlightened Sound Daemon)]]></flag>
<flag name="esoob"><![CDATA[Adds support for Easysoft OOD database]]></flag>
<flag name="ethereal"><![CDATA[Adds support for ethereal wiretap log support in kismet]]></flag>
<flag name="ev6"><![CDATA[Assume Alpha processor is EV6 or better]]></flag>
<flag name="evo"><![CDATA[Adds support for evolution in gnumeric and multisync]]></flag>
<flag name="examples"><![CDATA[Install example source code]]></flag>
<flag name="exif"><![CDATA[Adds support for reading EXIF headers from JPEG and TIFF images]]></flag>
<flag name="expat"><![CDATA[Enable the use of dev-libs/expat]]></flag>
<flag name="fam"><![CDATA[Enable FAM support]]></flag>
<flag name="fastcgi"><![CDATA[Add support for the FastCGI interface]]></flag>
<flag name="fbcon"><![CDATA[Adds framebuffer support for the console, via the kernel]]></flag>
<flag name="fdftk"><![CDATA[Add supports for Adobe's FDF toolkit.]]></flag>
<flag name="ffmpeg"><![CDATA[Enable ffmpeg support]]></flag>
<flag name="fftw"><![CDATA[Use FFTW library for computing Fourier transforms]]></flag>
<flag name="filepro"><![CDATA[Adds support for filePro databases]]></flag>
<flag name="firebird"><![CDATA[Adds support for the Firebird relational database]]></flag>
<flag name="flac"><![CDATA[Adds support for the flac audio codec]]></flag>
<flag name="flash"><![CDATA[Adds support for creating flash files using Ming]]></flag>
<flag name="flatfile"><![CDATA[Adds dbm support for flat files]]></flag>
<flag name="foomaticdb"><![CDATA[Adds support for the foomatic printing driver database]]></flag>
<flag name="fortran"><![CDATA[Adds support for fortran (formally f77)]]></flag>
<flag name="freetds"><![CDATA[Adds support for the TDS protocol to connect to MSSQL/Sybase databases]]></flag>
<flag name="freewnn"><![CDATA[Adds support for FreeWnn kana to kanji conversion engine]]></flag>
<flag name="frontbase"><![CDATA[Adds support for the frontbase sql server]]></flag>
<flag name="ftp"><![CDATA[Adds FTP support]]></flag>
<flag name="gb"><![CDATA[Adds support for Gnome Basic to gnumeric]]></flag>
<flag name="gcj"><![CDATA[Enable building with gcj]]></flag>
<flag name="gd"><![CDATA[Adds support for media-libs/gd (to generate graphics on the fly)]]></flag>
<flag name="gd-external"><![CDATA[Use the external version of gd rather than the bundled one (possibly dangerous)]]></flag>
<flag name="gdbm"><![CDATA[Adds support for sys-libs/gdbm (GNU database libraries)]]></flag>
<flag name="geoip"><![CDATA[Add geoip support]]></flag>
<flag name="ggi"><![CDATA[Adds support for media-libs/libggi (non-X video api/drivers)]]></flag>
<flag name="gif"><![CDATA[Adds GIF image support]]></flag>
<flag name="ginac"><![CDATA[Adds sci-mathematics/ginac (symbolic math) support]]></flag>
<flag name="glut"><![CDATA[Build an OpenGL plugin using the GLUT library]]></flag>
<flag name="gmp"><![CDATA[Adds support for dev-libs/gmp (GNU MP library)]]></flag>
<flag name="gnome"><![CDATA[Adds GNOME support]]></flag>
<flag name="gnustep"><![CDATA[Adds integration with GNUstep environment]]></flag>
<flag name="gnutls"><![CDATA[Adds support for net-libs/gnutls]]></flag>
<flag name="gphoto2"><![CDATA[Adds digital camera support]]></flag>
<flag name="gpm"><![CDATA[Adds support for sys-libs/gpm (Console-based mouse driver)]]></flag>
<flag name="gps"><![CDATA[Adds support for Global Positioning System]]></flag>
<flag name="gstreamer"><![CDATA[Adds support for media-libs/gstreamer (Streaming media)]]></flag>
<flag name="gtk"><![CDATA[Adds support for x11-libs/gtk+ (The GIMP Toolkit)]]></flag>
<flag name="gtk2"><![CDATA[Use gtk+-2.0.0 over gtk+-1.2 in cases where a program supports both.]]></flag>
<flag name="gtkhtml"><![CDATA[Adds support for gnome-extra/gtkhtml]]></flag>
<flag name="guile"><![CDATA[Adds support for dev-util/guile (interpreter for Scheme)]]></flag>
<flag name="hal"><![CDATA[Enable Hardware Abstraction Layer (HAL) support]]></flag>
<flag name="hardened"><![CDATA[activate default security enhancements for toolchain (gcc, glibc, binutils)]]></flag>
<flag name="hardenedphp"><![CDATA[include the hardened php security patch for the php group of ebuilds]]></flag>
<flag name="howl"><![CDATA[Enable howl support, enables DNS Service Discovery (DNS-SD)]]></flag>
<flag name="hyperwave-api"><![CDATA[Adds support for Hyperwave document storage system]]></flag>
<flag name="ibm"><![CDATA[Add support for IBM ppc64 specific systems]]></flag>
<flag name="icc"><![CDATA[Add support for the Intel C++ Compiler (does _not_ set $CC)]]></flag>
<flag name="iconv"><![CDATA[Enable support for the iconv character set conversion library]]></flag>
<flag name="icq"><![CDATA[Enable ICQ IM protocol support]]></flag>
<flag name="idn"><![CDATA[Enable support for Internationalized Domain Names]]></flag>
<flag name="ieee1394"><![CDATA[Enable FireWire/iLink IEEE1394 support (dv, camera, ...)]]></flag>
<flag name="ifc"><![CDATA[use ifc instead of g77 to build]]></flag>
<flag name="imagemagick"><![CDATA[Enables support for Imagemagick (image converter)]]></flag>
<flag name="imap"><![CDATA[Adds support for IMAP]]></flag>
<flag name="imlib"><![CDATA[Adds support for imlib, an image loading and rendering library]]></flag>
<flag name="informix"><![CDATA[Adds support for Informix database]]></flag>
<flag name="ingres"><![CDATA[Adds support for Ingres database]]></flag>
<flag name="inifile"><![CDATA[Adds dbm support for .ini files]]></flag>
<flag name="innodb"><![CDATA[Adds innodb support for mySQL (transaction support)]]></flag>
<flag name="interbase"><![CDATA[Adds support for Interbase database]]></flag>
<flag name="iodbc"><![CDATA[Adds support for iODBC library]]></flag>
<flag name="ipv6"><![CDATA[Adds support for IP version 6]]></flag>
<flag name="jabber"><![CDATA[Enable jabber IM protocol support]]></flag>
<flag name="jack"><![CDATA[Adds support for the JACK Audio Connection Kit]]></flag>
<flag name="java"><![CDATA[Adds support for Java]]></flag>
<flag name="javascript"><![CDATA[enable javascript support]]></flag>
<flag name="jikes"><![CDATA[Compile Java source code with jikes (faster)]]></flag>
<flag name="joystick"><![CDATA[Add support for joysticks in all packages]]></flag>
<flag name="jpeg"><![CDATA[Adds JPEG image support]]></flag>
<flag name="junit"><![CDATA[Adds junit awareness -- useful for developers.]]></flag>
<flag name="kde"><![CDATA[Adds support for kde-base/kde (K Desktop Enviroment)]]></flag>
<flag name="kdeenablefinal"><![CDATA[Makes kde ebuilds use the enable-final flag, yielding big compilation speedups at the cost of very heavy mem usage]]></flag>
<flag name="kdexdeltas"><![CDATA[Makes kde ebuilds download binary diffs rather than entire new tarballs for every new release]]></flag>
<flag name="kerberos"><![CDATA[Adds kerberos support]]></flag>
<flag name="krb4"><![CDATA[Adds optional kerberos 4 compatibility support]]></flag>
<flag name="ladcca"><![CDATA[Adds Linux Audio Developer's Configuration and Connection API support (LADCCA)]]></flag>
<flag name="lapack"><![CDATA[adds support for the virtual/lapack numerical library]]></flag>
<flag name="lcms"><![CDATA[Adds lcms support (color management engine)]]></flag>
<flag name="ldap"><![CDATA[Adds LDAP support (Lightweight Directory Access Protocol)]]></flag>
<flag name="leim"><![CDATA[Adds input methods support to Emacs]]></flag>
<flag name="lesstif"><![CDATA[Use lesstif over openmotif in cases where a program supports both]]></flag>
<flag name="libcaca"><![CDATA[Add support for colored ASCII-art graphics]]></flag>
<flag name="libedit"><![CDATA[Use the libedit library (replacement for readline)]]></flag>
<flag name="libg++"><![CDATA[Adds C++ modules in dev-db/postgresql (libpq++)]]></flag>
<flag name="libgda"><![CDATA[Adds GNU Data Access (CORBA wrapper) support for gnumeric]]></flag>
<flag name="libwww"><![CDATA[Adds libwww support (General purpose WEB API)]]></flag>
<flag name="lirc"><![CDATA[Adds support for lirc (Linux's Infra-Red Remote Control)]]></flag>
<flag name="livecd"><![CDATA[!!internal use only!! DO NOT SET THIS FLAG YOURSELF!, used during livecd building.]]></flag>
<flag name="lm_sensors"><![CDATA[Adds linux lm_sensors (hardware sensors) support]]></flag>
<flag name="lua"><![CDATA[Enable Lua scripting support]]></flag>
<flag name="m17n-lib"><![CDATA[Enable m17n-lib support]]></flag>
<flag name="mad"><![CDATA[Adds support for mad (high-quality mp3 decoder library and cli frontend)]]></flag>
<flag name="maildir"><![CDATA[Adds support for maildir (~/.maildir) style mail spools]]></flag>
<flag name="mailwrapper"><![CDATA[Adds mailwrapper support to allow multiple MTAs to be installed]]></flag>
<flag name="matroska"><![CDATA[Adds support for the matroska container format]]></flag>
<flag name="matrox"><![CDATA[Adds Matrox MGA support to mplayer]]></flag>
<flag name="mbox"><![CDATA[Adds support for mbox (/var/spool/mail) style mail spools]]></flag>
<flag name="mcal"><![CDATA[Adds support for MCAL calendar system]]></flag>
<flag name="mcve"><![CDATA[Support for the MCVE credit card payment system]]></flag>
<flag name="memlimit"><![CDATA[Adds memory usage limiting in supporting programs]]></flag>
<flag name="mhash"><![CDATA[Adds support for the mhash library]]></flag>
<flag name="migemo"><![CDATA[enable migemo support for Japanese]]></flag>
<flag name="mikmod"><![CDATA[Adds libmikmod support to allow playing of SoundTracker-style music files]]></flag>
<flag name="milter"><![CDATA[Adds sendmail mail filter (milter) support]]></flag>
<flag name="mime"><![CDATA[Adds MIME support]]></flag>
<flag name="ming"><![CDATA[Adds support for ming library for creating flash format files]]></flag>
<flag name="minimal"><![CDATA[Install a very minimal build (disables, for example, plugins, fonts, most drivers, non-critical features)]]></flag>
<flag name="mmap"><![CDATA[Adds mmap support]]></flag>
<flag name="mmx"><![CDATA[Adds support for optimizations for Pentium MMX and Athlon class processors]]></flag>
<flag name="mng"><![CDATA[Adds support for libmng (MNG images)]]></flag>
<flag name="mnogosearch"><![CDATA[Adds support for the mnoGoSearch search engine]]></flag>
<flag name="mono"><![CDATA[Build Mono bindings to support dotnet type stuff]]></flag>
<flag name="motif"><![CDATA[Adds motif support (x11-libs/openmotif x11-libs/lesstif)]]></flag>
<flag name="mozilla"><![CDATA[Adds mozilla support]]></flag>
<flag name="mp3"><![CDATA[Add support for reading mp3 files]]></flag>
<flag name="mpeg"><![CDATA[Adds libmpeg3 support to various packages.]]></flag>
<flag name="mpi"><![CDATA[Adds MPI (Message Passing Interface) layer to the apps that support it.]]></flag>
<flag name="msession"><![CDATA[Adds support for msession daemon]]></flag>
<flag name="msn"><![CDATA[Enable MSN Messenger IM protocol support]]></flag>
<flag name="msql"><![CDATA[Adds support for the MSQL database server]]></flag>
<flag name="mssql"><![CDATA[Adds support for Microsoft SQL Server database]]></flag>
<flag name="mule"><![CDATA[Adds multi-language support to XEmacs]]></flag>
<flag name="multilib"><![CDATA[On 64bit systems, if you want to be able to compile 32bit and 64bit binaries]]></flag>
<flag name="mysql"><![CDATA[Adds mySQL support]]></flag>
<flag name="mysqli"><![CDATA[Adds support for the improved mySQL libraries]]></flag>
<flag name="nas"><![CDATA[Adds support for network audio sound]]></flag>
<flag name="ncurses"><![CDATA[Adds ncurses support (console display library)]]></flag>
<flag name="netboot"><![CDATA[Enables network booting]]></flag>
<flag name="netcdf"><![CDATA[Enable NetCDF data format support]]></flag>
<flag name="neXt"><![CDATA[Enable neXt toolkit]]></flag>
<flag name="nhc98"><![CDATA[Use the nhc98 Haskell compiler instead of GHC if the package supports it]]></flag>
<flag name="nis"><![CDATA[Support for NIS/YP services]]></flag>
<flag name="nls"><![CDATA[Adds Native Language Support (using gettext - GNU locale utilities)]]></flag>
<flag name="nocd"><![CDATA[Tells emerge to install all files required to run the application without a CD mounted]]></flag>
<flag name="nocxx"><![CDATA[Disable support for C++ (DONT USE THIS UNLESS YOU KNOW WHAT YOU'RE DOING)]]></flag>
<flag name="nptl"><![CDATA[Enable support for Native POSIX Threads Library, the new threading module (requires linux-2.6 or better usually)]]></flag>
<flag name="nsplugin"><![CDATA[Builds plugins for Netscape compatible browsers]]></flag>
<flag name="ocaml"><![CDATA[Adds support/bindings for the Ocaml language]]></flag>
<flag name="oci8"><![CDATA[Adds Oracle 8 Support]]></flag>
<flag name="odbc"><![CDATA[Adds ODBC Support (Open DataBase Connectivity)]]></flag>
<flag name="offensive"><![CDATA[Enables potentially offensive items in packages]]></flag>
<flag name="ofx"><![CDATA[Enable support for importing (and exporting) OFX (Open Financial eXchange) data files]]></flag>
<flag name="ogg"><![CDATA[Adds support for the Ogg container format (commonly used by Vorbis, Theora and flac)]]></flag>
<flag name="oggvorbis"><![CDATA[Adds support for the OggVorbis audio encoding - DEPRECATED useflag ]]></flag>
<flag name="openal"><![CDATA[Adds support for the Open Audio Library]]></flag>
<flag name="opengl"><![CDATA[Adds support for OpenGL]]></flag>
<flag name="oracle7"><![CDATA[Adds support for Oracle 7]]></flag>
<flag name="oracle"><![CDATA[Enable oracle support]]></flag>
<flag name="osc"><![CDATA[Enables support for Open Sound Control]]></flag>
<flag name="oscar"><![CDATA[Enable Oscar (AIM/ICQ) IM protocol support]]></flag>
<flag name="oss"><![CDATA[Adds support for OSS (Open Sound System)]]></flag>
<flag name="ovrimos"><![CDATA[Adds support for the Ovrimos Database engine]]></flag>
<flag name="pam"><![CDATA[Adds support PAM (Pluggable Authentication Modules) - DANGEROUS to arbitrarily flip]]></flag>
<flag name="pcmcia"><![CDATA[Adds support for PCMCIA slots/devices found on laptop computers]]></flag>
<flag name="pcntl"><![CDATA[Adds support for process creation functions]]></flag>
<flag name="pcre"><![CDATA[Adds support for Perl Compatible Regular Expressions]]></flag>
<flag name="pda"><![CDATA[Adds support for portable devices.]]></flag>
<flag name="pdflib"><![CDATA[Adds support for PDF (Portable Document Format)]]></flag>
<flag name="perl"><![CDATA[Adds support/bindings for the Perl language.]]></flag>
<flag name="pfpro"><![CDATA[Adds support for Verisign Payflow Pro]]></flag>
<flag name="php"><![CDATA[Include support for php]]></flag>
<flag name="pic"><![CDATA[Build Position Independent Code.  Do not utilize this flag unless you know what you're doing.]]></flag>
<flag name="plotutils"><![CDATA[Adds plotutils support to gnuplot (library for 2-D vector graphics)]]></flag>
<flag name="png"><![CDATA[Adds support for libpng (PNG images)]]></flag>
<flag name="portaudio"><![CDATA[Adds support for the crossplatform portaudio audio API]]></flag>
<flag name="posix"><![CDATA[Adds support for POSIX-compatible functions]]></flag>
<flag name="postgres"><![CDATA[Adds support for the postgresql database]]></flag>
<flag name="ppds"><![CDATA[Adds support for automatically generated ppd (printing driver) files]]></flag>
<flag name="prelude"><![CDATA[Adds support/bindings for the Prelude Intrusion Detection System]]></flag>
<flag name="profile"><![CDATA[Adds profile support to builds of packages (will likely vary from ebuild to ebuild in support)]]></flag>
<flag name="python"><![CDATA[Adds support/bindings for the Python language]]></flag>
<flag name="qdbm"><![CDATA[Adds support for the qdbm library]]></flag>
<flag name="qt"><![CDATA[Adds support for the Qt library.]]></flag>
<flag name="quicktime"><![CDATA[Adds support for OpenQuickTime]]></flag>
<flag name="radius"><![CDATA[Adds support for RADIUS]]></flag>
<flag name="readline"><![CDATA[enables support for libreadline, a GNU line-editing library that most everyone wants.]]></flag>
<flag name="recode"><![CDATA[enables support for the GNU recode library]]></flag>
<flag name="ruby"><![CDATA[Adds support/bindings for the Ruby language]]></flag>
<flag name="samba"><![CDATA[Adds support for SAMBA]]></flag>
<flag name="sapdb"><![CDATA[Adds support for SAP DB]]></flag>
<flag name="sasl"><![CDATA[Adds support for the Simple Authentication and Security Layer]]></flag>
<flag name="scanner"><![CDATA[Adds support for scanner hardware (e.g. build the sane frontend in kdegraphics)]]></flag>
<flag name="sdl"><![CDATA[Adds support for Simple Direct Layer (media library)]]></flag>
<flag name="selinux"><![CDATA[!!internal use only!! Security Enhanced Linux support, this must be set by the selinux profile or breakage will occur]]></flag>
<flag name="session"><![CDATA[Adds persistent session support]]></flag>
<flag name="sharedext"><![CDATA[Adds support for building shared extensions in php]]></flag>
<flag name="sharedmem"><![CDATA[Adds support for shared memory use]]></flag>
<flag name="shorten"><![CDATA[Adds support for the shorten audio compressor]]></flag>
<flag name="simplexml"><![CDATA[support for simplexml]]></flag>
<flag name="skey"><![CDATA[Enable S/Key (Single use password) authentication support]]></flag>
<flag name="slang"><![CDATA[Adds support for the slang text display library (it's like ncurses, but different)]]></flag>
<flag name="slp"><![CDATA[Adds Service Locator Protocol support to CUPS]]></flag>
<flag name="smartcard"><![CDATA[Enables smartcard support]]></flag>
<flag name="sndfile"><![CDATA[Adds support for libsndfile]]></flag>
<flag name="snmp"><![CDATA[Adds support for the Simple Network Management Protocol if available]]></flag>
<flag name="soap"><![CDATA[Adds support for SOAP]]></flag>
<flag name="sockets"><![CDATA[Adds support for tcp/ip sockets]]></flag>
<flag name="socks5"><![CDATA[Adds support for the socks5 proxy]]></flag>
<flag name="solid"><![CDATA[Adds support for the Solid database engine]]></flag>
<flag name="source"><![CDATA[Zip the sources and install them]]></flag>
<flag name="sox"><![CDATA[Adds support for Sound eXchange (SoX)]]></flag>
<flag name="speex"><![CDATA[Adds support for the speex audio codec]]></flag>
<flag name="spell"><![CDATA[Adds dictionary support]]></flag>
<flag name="spl"><![CDATA[Adds support for the Standard PHP Library]]></flag>
<flag name="sqlite"><![CDATA[Adds support for sqlite - embedded sql database]]></flag>
<flag name="sse"><![CDATA[fast floating point optimization for PentiumIII+ class chips]]></flag>
<flag name="ssl"><![CDATA[Adds support for Secure Socket Layer connections]]></flag>
<flag name="static"><![CDATA[!!do not set this during bootstrap!! Causes binaries to be statically linked instead of dynamically]]></flag>
<flag name="svg"><![CDATA[Adds support for SVG (Scalable Vector Graphics http://www.w3.org/TR/SVG ).  This option is mainly intended for users that tend to browse multimedia sites frequently.]]></flag>
<flag name="svga"><![CDATA[Adds support for SVGAlib (graphics library)]]></flag>
<flag name="sybase"><![CDATA[Adds support for the Sybase SQL Database Server]]></flag>
<flag name="sybase-ct"><![CDATA[Adds support for Sybase-CT]]></flag>
<flag name="symlink"><![CDATA[Force kernel ebuilds to automatically update the /usr/src/linux symlink.]]></flag>
<flag name="sysvipc"><![CDATA[Support for System V-compatible inter-process communication]]></flag>
<flag name="szip"><![CDATA[Use the szip compression library]]></flag>
<flag name="tcltk"><![CDATA[Support for Tcl and/or Tk]]></flag>
<flag name="tcpd"><![CDATA[Adds support for TCP wrappers]]></flag>
<flag name="test"><![CDATA[Work around to pull in packages needed to run with FEATURES=maketest / FEATURES=test]]></flag>
<flag name="tetex"><![CDATA[Adds support for teTeX]]></flag>
<flag name="theora"><![CDATA[Adds support for the Theora Video Compression Codec]]></flag>
<flag name="threads"><![CDATA[Adds threads support for various packages. Usually pthreads]]></flag>
<flag name="tidy"><![CDATA[Adds support for HTML Tidy]]></flag>
<flag name="tiff"><![CDATA[Adds support for the tiff image format]]></flag>
<flag name="tokenizer"><![CDATA[Adds support for the PHP file parser]]></flag>
<flag name="truetype"><![CDATA[Adds support for FreeType and/or FreeType2 fonts]]></flag>
<flag name="uclibc"><![CDATA[Enable uclibc specific patches and build or link uclibc]]></flag>
<flag name="unicode"><![CDATA[Adds support for Unicode]]></flag>
<flag name="usb"><![CDATA[Adds USB support to applications that have optional USB support (e.g. cups)]]></flag>
<flag name="v4l"><![CDATA[Enables video4linux support]]></flag>
<flag name="vanilla"><![CDATA[Do not add extra patches which change default behaviour]]></flag>
<flag name="vcd"><![CDATA[Video CD support]]></flag>
<flag name="verbose"><![CDATA[effects vary across packages; generally used to enable extra informational output during a build or at runtime]]></flag>
<flag name="vhosts"><![CDATA[Adds support for installing web-based applications into a virtual-hosting environment]]></flag>
<flag name="videos"><![CDATA[Tells portage to install optional video files (used in some games)]]></flag>
<flag name="voodoo3"><![CDATA[Adds support for 3Dfx's Voodoo3 video chipset, else defaults to Voodoo4/5 support if not in USE.]]></flag>
<flag name="vorbis"><![CDATA[Adds support for the OggVorbis audio codec]]></flag>
<flag name="wddx"><![CDATA[Adds support for WDDX]]></flag>
<flag name="wifi"><![CDATA[Enable wireless network functions]]></flag>
<flag name="win32codecs"><![CDATA[use win32codecs package for dll avi decoding support (wmv and what not)]]></flag>
<flag name="wmf"><![CDATA[Adds support for the wmf vector image format]]></flag>
<flag name="wxwindows"><![CDATA[Adds support for wxWindows/wxGTK]]></flag>
<flag name="xface"><![CDATA[Adds xface support used to allow a small image of xface format to be included in an email via the header 'X-Face'.]]></flag>
<flag name="xine"><![CDATA[Add support for the XINE movie libraries]]></flag>